#!/bin/sh

set -e
exec 2>&1

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVICE_USER="${CONTAINER_USER:-vscode}"

: "${SERVICE_NAME:?}"

install -d -o "${SERVICE_USER}" -g "${SERVICE_USER}" -m 0755 "/var/log/${SERVICE_NAME}"
exec su-exec "${SERVICE_USER}" /usr/local/bin/start-service.sh
