services:
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    depends_on:
      - otel-collector
      - jaeger
      - grafana
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=basic b3RlbDpvdGVs
      - npm_config_userconfig=/usr/src/service/.npmrc.local
      - GEOIP_CITY_FILE=/usr/share/GeoIP/GeoIP2-City.mmdb
      - GEOIP_ISP_FILE=/usr/share/GeoIP/GeoIP2-ISP.mmdb
    restart: always
    volumes:
      - "../:/usr/src/service"
    working_dir: /usr/src/service

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0@sha256:42a27d048c35720cf590243223543671e9d9f1ad8537d5a35c4b748fc8ebe873
    command:
      - "--config=/etc/otel-collector-config.yaml"
    depends_on:
      - victoriametrics
      - jaeger
      - loki
    restart: always
    volumes:
      - ./.docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  jaeger:
    image: ghcr.io/myrotvorets/codespaces/jaeger:latest@sha256:c0a45e4260e6478f96ecca21f05dd629128a11d1fe2940bedbf79e7a0409e0f6
    restart: always
    volumes:
      - jaegerdata:/badger

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.100.1@sha256:a7a22bd241e5a350b7c38a6b66d7074af29831742a5819fa1597ef44d714cd71
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    restart: always
    volumes:
      - vmdata:/storage

  loki:
    image: grafana/loki:3.0.0@sha256:757b5fadf816a1396f1fea598152947421fa49cb8b2db1ddd2a6e30fae003253
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    restart: always

  grafana:
    image: grafana/grafana:10.4.2@sha256:7d5faae481a4c6f436c99e98af11534f7fd5e8d3e35213552dd1dd02bc393d2e
    depends_on:
      - victoriametrics
      - loki
    restart: always
    volumes:
      - grafanadata:/var/lib/grafana
      - ./.docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./.docker/grafana/dashboards/ipgeo.json:/var/lib/grafana/dashboards/ipgeo.json

  swagger:
    image: swaggerapi/swagger-ui:v5.15.0@sha256:95dda0f6eefa244a2d9dd05a76eaf442ef757f4750d81e6b98ed5af746e959b0
    environment:
      - SWAGGER_JSON_URL=/specs/ipgeo-private.yaml
      - BASE_URL=/swagger
      - DISPLAY_REQUEST_DURATION=true
      - DEFAULT_MODELS_EXPAND_DEPTH=100
      - DEFAULT_MODEL_EXPAND_DEPTH=100
      - DEEP_LINKING=true
      - VALIDATOR_URL=none

volumes:
  grafanadata:
  jaegerdata:
  vmdata:
