services:
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    depends_on:
      - otel-collector
      - jaeger
      - grafana
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=basic b3RlbDpvdGVs
      - npm_config_userconfig=/usr/src/service/.npmrc.local
      - GEOIP_CITY_FILE=/usr/share/GeoIP/GeoIP2-City.mmdb
      - GEOIP_ISP_FILE=/usr/share/GeoIP/GeoIP2-ISP.mmdb
    restart: always
    volumes:
      - "../:/usr/src/service"
    working_dir: /usr/src/service

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.137.0@sha256:886722fe0f37af9d1fe24d29529253ec59fbf263b3b1df4facaf221373e19d23
    command:
      - "--config=/etc/otel-collector-config.yaml"
    depends_on:
      - victoriametrics
      - jaeger
      - loki
    restart: always
    volumes:
      - ./.docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  jaeger:
    image: ghcr.io/myrotvorets/codespaces/jaeger:latest@sha256:1823b417a23f9bbb23c3698e9c150ecd2df0e720737a67c19069c7175eb05982
    restart: always
    volumes:
      - jaegerdata:/badger

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.127.0@sha256:d6b6fed9b6d69741d0ac59baaafa5bb7f4ce0ee76f8cd78181f44c72b452d240
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    restart: always
    volumes:
      - vmdata:/storage

  loki:
    image: grafana/loki:3.5.7@sha256:0eaee7bf39cc83aaef46914fb58f287d4f4c4be6ec96b86c2ed55719a75e49c8
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    restart: always

  grafana:
    image: grafana/grafana:12.2.0@sha256:74144189b38447facf737dfd0f3906e42e0776212bf575dc3334c3609183adf7
    depends_on:
      - victoriametrics
      - loki
    restart: always
    volumes:
      - grafanadata:/var/lib/grafana
      - ./.docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./.docker/grafana/dashboards/ipgeo.json:/var/lib/grafana/dashboards/ipgeo.json

  swagger:
    image: swaggerapi/swagger-ui:v5.29.3@sha256:9c2688be89e275bbc80b85ffedf52883233cbd1ec4636faff3eb618b6420acf2
    environment:
      - SWAGGER_JSON_URL=/specs/ipgeo-private.yaml
      - BASE_URL=/swagger
      - DISPLAY_REQUEST_DURATION=true
      - DEFAULT_MODELS_EXPAND_DEPTH=100
      - DEFAULT_MODEL_EXPAND_DEPTH=100
      - DEEP_LINKING=true
      - VALIDATOR_URL=none

volumes:
  grafanadata:
  jaegerdata:
  vmdata:
