services:
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    depends_on:
      - otel-collector
      - jaeger
      - grafana
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=basic b3RlbDpvdGVs
      - npm_config_userconfig=/usr/src/service/.npmrc.local
      - GEOIP_CITY_FILE=/usr/share/GeoIP/GeoIP2-City.mmdb
      - GEOIP_ISP_FILE=/usr/share/GeoIP/GeoIP2-ISP.mmdb
    restart: always
    volumes:
      - "../:/usr/src/service"
    working_dir: /usr/src/service

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0@sha256:42a27d048c35720cf590243223543671e9d9f1ad8537d5a35c4b748fc8ebe873
    command:
      - "--config=/etc/otel-collector-config.yaml"
    depends_on:
      - victoriametrics
      - jaeger
      - loki
    restart: always
    volumes:
      - ./.docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  jaeger:
    image: ghcr.io/myrotvorets/codespaces/jaeger:latest@sha256:d6f3b3479af267cca957a18505e8d8d6e68e98a7ebf4985f608c3885193f5ea7
    restart: always
    volumes:
      - jaegerdata:/badger

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.99.0@sha256:e3e18b05a2c056ac2daa0215b284f0583dcb47c8a0db2965a8eaf9f219535734
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    restart: always
    volumes:
      - vmdata:/storage

  loki:
    image: grafana/loki:2.9.6@sha256:6ca6e2cd3b6f45e0eb298da2920610fde63ecd8ab6c595d9c941c8559d1d9407
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    restart: always

  grafana:
    image: grafana/grafana:10.4.1@sha256:753bbb971071480d6630d3aa0d55345188c02f39456664f67c1ea443593638d0
    depends_on:
      - victoriametrics
      - loki
    restart: always
    volumes:
      - grafanadata:/var/lib/grafana
      - ./.docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./.docker/grafana/dashboards/ipgeo.json:/var/lib/grafana/dashboards/ipgeo.json

  swagger:
    image: swaggerapi/swagger-ui:v5.13.0@sha256:2d82a0c2468cf6bc4f4e62f65e8554718673064831f18ec60ea7043333004ca1
    environment:
      - SWAGGER_JSON_URL=/specs/ipgeo-private.yaml
      - BASE_URL=/swagger
      - DISPLAY_REQUEST_DURATION=true
      - DEFAULT_MODELS_EXPAND_DEPTH=100
      - DEFAULT_MODEL_EXPAND_DEPTH=100
      - DEEP_LINKING=true
      - VALIDATOR_URL=none

volumes:
  grafanadata:
  jaegerdata:
  vmdata:
